name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
          
      - name: Check folder on server
        run: ssh root@69.62.78.171 'mkdir -p /var/www/html'
          
      - name: Deploy to Hostinger
        run: |
          rsync -avz --delete build/ root@69.62.78.171:/var/www/html/
          
      - name: Verify deployment
        run: |
          echo "Deployed successfully to Hostinger server at $(date)" 